services:
  postgres-access:
    image: bitnami/postgresql:latest
    env_file: ../database/.env
    volumes:
      - ../database/scripts:/scripts  
    ports:
      - "5433:5432" 

  flask-api:
    image: python:3.9.2-slim-buster
    volumes:
      - ../api/requirements.txt:/requirements.txt
      - ../api/api/:/api/
      - ../api/api/db_interaction/:/api/db_interaction/
      - ../api/api/messages/:/api/messages/
      - ../api/api/security/:/api/security/
      - ../api/common/utils:/common/utils/
      - ../api/gunicorn.conf.py:/gunicorn.conf.py
      - ../api/entrypoint.sh:/entrypoint.sh
    env_file: ../api/.env
    ports:
      - "8080:8080"
    entrypoint: ["/bin/bash", "/entrypoint.sh"]  # Set entrypoint to the script

  frontend-react:
    image: node:16.15
    volumes:
      - ../frontend/entrypoint.sh:/entrypoint.sh
      - ../frontend/dist/index.html:/dist/index.html
      - ../frontend/dist/assets/images:/dist/assets/images
      - ../frontend/dist/assets/fonts/Merriweather:/dist/assets/fonts/Merriweather
      - ../frontend/dist/assets/fonts/Open_Sans:/dist/assets/fonts/Open_Sans
      - ../frontend/dist/assets/fonts/Open_Sans/static:/dist/assets/fonts/Open_Sans/static
    env_file:
      - ../frontend/.env/
    ports:
      - "4000:4000"
    entrypoint: ["/bin/bash", "/entrypoint.sh"] 

    