events {}

http {
	server {
		listen 80;
		server_name _;
		
		location / {
			return 301 https://$host$request_uri;
		}
	}
	
	server {
		listen 443 ssl;
		server_name copernicus-model-atlas.uu.nl; 

        ssl_certificate /etc/nginx/certificates/hyde-portal_geo_uu_nl.crt;
        ssl_certificate_key /etc/nginx/certificates/hyde-portal_geo_uu_nl.key;
        ssl_trusted_certificate /etc/nginx/certificates/CACert.crt;

        location / {
            proxy_pass http://fe:80; # Proxy_pass to Node.js application internally on port 80
        }

    }
}
	
