// keywords.js

// Sustainability-related keywords
export const keywords = [
    'Renewable Energy',
    'Climate Change',
    'Sustainable Development',
    'Carbon Footprint',
    'Green Energy',
    'Recycling',
    'Energy Efficiency',
    'Eco-Friendly',
    'Solar Power',
    'Wind Energy',
    'Water Conservation',
    'Sustainable Agriculture',
    'Circular Economy',
    'Zero Waste',
    'Green Building',
    'Carbon Neutral',
    'Sustainable Transportation',
    'Sustainable Cities',
];

export const blankForm = {
    modelName: "",
    keywords: [],
    modellerName0: "",
    modellerUrl0: "",
    modellerName1: "",
    modellerUrl1: "",
    modellerName2: "",
    modellerUrl2: "",
    modellerName3: "",
    modellerUrl3: "",
    modellerName4: "",
    modellerUrl4: "",
    nbModellers: 1,
    shortDescr: "",
    icon: "",
    longDescr: "",
    explanFig: "",
    explanFigCaption: "",
    linkName0: "",
    linkUrl0: "",
    linkName1: "",
    linkUrl1: "",
    linkName2: "",
    linkUrl2: "",
    linkName3: "",
    linkUrl3: "",
    linkName4: "",
    linkUrl4: "",
    nbLinks: 1,
    theoryText: "",
    theoryFig: "",
    theoryFigDesc: "",
    resText: "",
    resFig: "",
    resFigDesc: "",
    boxTitle0: "",
    boxFileTitle0: "",
    boxFile0: "",
    boxDescr0: "",
    boxTitle1: "",
    boxFileTitle1: "",
    boxFile1: "",
    boxDescr1: "",
    boxTitle2: "",
    boxFileTitle2: "",
    boxFile2: "",
    boxDescr2: "",
    boxTitle3: "",
    boxFileTitle3: "",
    boxFile3: "",
    boxDescr3: "",
    nbBoxes: 1,
    methodsDesc: "",
    methodsFile: "",
    colofonCite: "",
    colofonLicence: "",
    colofonAddition: "",
};

export const mandFields = [
    "modelName",
    "modellerName0",
    "descr",
    "explanFig",
    "explanFigCaption",
    "theoryText",
    "resText",
    "boxTitle0",
    "boxFigTitle0",
    "boxfig0",
    "boxDescr0",
    "colofonCite",
    "colofonLicence",
];

export const fieldNameMapping = {
    modelName: "Model Name",
    modellerName0: "Modeller Name",
    descr: "Description",
    explanFig: "Explanation Figure",
    explanFigCaption: "Expalnatory Figure Caption",
    theoryText: "Theory Text",
    resText: "Results Text",
    boxTitle0: "Box Title",
    boxFigTitle0: "Box Figure Title",
    boxfig0: "Box Figure",
    boxDescr0: "Box Description",
    colofonCite: "Colophon Citation",
    colofonLicence: "Colophon License",
};
