// keywords.js

// Sustainability-related keywords
export const keywords = [
    'Renewable Energy',
    'Climate Change',
    'Sustainable Development',
    'Carbon Footprint',
    'Green Energy',
    'Recycling',
    'Energy Efficiency',
    'Eco-Friendly',
    'Solar Power',
    'Wind Energy',
    'Water Conservation',
    'Sustainable Agriculture',
    'Circular Economy',
    'Zero Waste',
    'Green Building',
    'Carbon Neutral',
    'Sustainable Transportation',
    'Sustainable Cities',
];

export const blankForm = {
    modelName: "",
    keywords: [],
    modellerName0: "",
    modellerUrl0: "",
    modellerName1: "",
    modellerUrl1: "",
    modellerName2: "",
    modellerUrl2: "",
    modellerName3: "",
    modellerUrl3: "",
    modellerName4: "",
    modellerUrl4: "",
    icon: "",
    descr: "",
    explanFig: "",
    explanFigCaption: "",
    linkName0: "",
    linkUrl0: "",
    linkName1: "",
    linkUrl1: "",
    linkName2: "",
    linkUrl2: "",
    linkName3: "",
    linkUrl3: "",
    linkName4: "",
    linkUrl4: "",
    theoryText: "",
    theoryFig: "",
    theoryFigDesc: "",
    resText: "",
    resFig: "",
    resFigDesc: "",
    boxTitle0: "",
    boxFigTitle0: "",
    boxfig0: "",
    boxDescr0: "",
    boxTitle1: "",
    boxFigTitle1: "",
    boxfig1: "",
    boxDescr1: "",
    boxTitle2: "",
    boxFigTitle2: "",
    boxfig2: "",
    boxDescr2: "",
    boxTitle3: "",
    boxFigTitle3: "",
    boxfig3: "",
    boxDescr3: "",
    methodsDesc: "",
    methodsFile: "",
    colofonCite: "",
    colofonLicence: "",
    colofonAddition: "",
};