-- Remove the table if it already exists
DROP TABLE IF EXISTS models;

-- Create the `models` table
CREATE TABLE models (
  id SERIAL PRIMARY KEY, 
  modelName TEXT NOT NULL,
  keywords TEXT[],
  modellerName0 TEXT,
  modellerUrl0 TEXT,
  modellerName1 TEXT,
  modellerUrl1 TEXT,
  modellerName2 TEXT,
  modellerUrl2 TEXT,
  modellerName3 TEXT,
  modellerUrl3 TEXT,
  modellerName4 TEXT,
  modellerUrl4 TEXT,
  icon BYTEA,
  descr TEXT,
  explanFig BYTEA,
  explanFigCaption TEXT,
  linkName0 TEXT,
  linkUrl0 TEXT,
  linkName1 TEXT,
  linkUrl1 TEXT,
  linkName2 TEXT,
  linkUrl2 TEXT,
  linkName3 TEXT,
  linkUrl3 TEXT,
  linkName4 TEXT,
  linkUrl4 TEXT,
  theoryText TEXT,
  theoryFig BYTEA,
  theoryFigDesc TEXT,
  resText TEXT,
  resFig BYTEA,
  resFigDesc TEXT,
  boxTitle0 TEXT,
  boxFigTitle0 TEXT,
  boxfig0 BYTEA,
  boxDescr0 TEXT,
  boxTitle1 TEXT,
  boxFigTitle1 TEXT,
  boxfig1 BYTEA,
  boxDescr1 TEXT,
  boxTitle2 TEXT,
  boxFigTitle2 TEXT,
  boxfig2 BYTEA,
  boxDescr2 TEXT,
  boxTitle3 TEXT,
  boxFigTitle3 TEXT,
  boxfig3 BYTEA,
  boxDescr3 TEXT,
  methodsDesc TEXT,
  methodsFile BYTEA,
  colofonCite TEXT,
  colofonLicence TEXT,
  colofonAddition TEXT
);
