apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgres-data-pvc
  namespace: geo-acc-modelatlas
  labels:
    app: postgres
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: netapp
  resources:
    requests:
      storage: 100Gi