apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: postgresql
  namespace: geo-acc-modelatlas
  labels:
    app: postgres
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgres
  template:
    metadata:
      labels:
        app: postgres
    spec:
      terminationGracePeriodSeconds: 30
      containers:
        - name: postgres
          image: postgres:16.1
          args:
            - "-c"
            - "data_directory=/mnt/postgresql-16/pgdata/data"
          env:
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgresql-secret
                  key: POSTGRES_PASSWORD
            - name: PGDATA
              value: /mnt/postgresql-16/pgdata/data
          volumeMounts:
            - name: pgdata
              mountPath: /mnt/postgresql-16/pgdata
            - name: pgbackup
              mountPath: /mnt/postgresql-16/pgbackup
          securityContext:
            fsGroup: 999
            runAsNonRoot: true
            allowPrivilegeEscalation: false
            capabilities:
              drop:
                - ALL
            seccompProfile:
              type: RuntimeDefault
      volumes:
        - name: pgdata
          persistentVolumeClaim:
            claimName: postgres-data-pvc
        - name: pgbackup
          persistentVolumeClaim:
            claimName: postgres-backup-pvc