apiVersion: v1
data:
  database-secret: W2RhdGFiYXNlXQ0KUEdQQVNTV09SRCA9IEFOVGVNQTg3Nl9udUFkV0U=
kind: Secret
metadata:
  labels:
    io.kompose.service: database-secret
  name: database-secret
type: Opaque
