apiVersion: v1
data:
  __init__.py: |
    from os import environ

    def safe_get_env_var(key):
        try:
            return environ[key]
        except KeyError:
            raise NameError(f"Missing {key} environment variable.")
kind: ConfigMap
metadata:
  labels:
    io.kompose.service: flask-api
  name: flask-api-cm5
