apiVersion: v1
data:
  __init__.py: ""
  message.py: |
    class Message:
        def __init__(self, text):
            self.text = text
            self.metadata = vars(Metadata())

    class Metadata:
        def __init__(self):
            self.api = "api_flask_python_hello-world"
            self.branch = "basic-role-based-access-control"
  messages_service.py: |
    from api.messages.message import Message


    def get_public_message():
        return Message("This is a public messag.")


    def get_protected_message():
        return Message("This is a protected message.")


    def get_admin_message():
        return Message("This is an admin message.")
  messages_views.py: |
    from flask import Blueprint

    from api.messages.messages_service import (
        get_public_message,
        get_protected_message,
        get_admin_message,
    )

    from api.security.guards import (
        authorization_guard,
        permissions_guard,
        admin_messages_permissions,
    )

    bp_name = "api-messages"
    bp_url_prefix = "/api/messages"
    bp = Blueprint(bp_name, __name__, url_prefix=bp_url_prefix)


    @bp.route("/public")
    def public():
        return vars(get_public_message())


    @bp.route("/protected")
    @authorization_guard
    def protected():
        return vars(get_protected_message())


    @bp.route("/admin")
    @authorization_guard
    @permissions_guard([admin_messages_permissions.read])
    def admin():
        return vars(get_admin_message())
kind: ConfigMap
metadata:
  labels:
    io.kompose.service: flask-api
  name: flask-api-cm3
