apiVersion: v1
data:
  AUTH0_AUDIENCE: https://hello-world.example.com
  AUTH0_DOMAIN: copernicus-model-atlas.eu.auth0.com
  CLIENT_ORIGIN_URL: https://frontend-geo-acc-modelatlas.apps.cl01.cp.its.uu.nl/public
kind: ConfigMap
metadata:
  labels:
    io.kompose.service: flask-api-flask-api-env
  name: flask-api-env
