apiVersion: apps.openshift.io/v1
kind: DeploymentConfig
metadata:
  labels:
    io.kompose.service: flask-api
  name: flask-api
spec:
  replicas: 1
  selector:
    io.kompose.service: flask-api
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        io.kompose.service: flask-api
    spec:
      containers:
        - command:
            - /bin/bash
            - /entrypoint.sh
          env:
            - name: AUTH0_AUDIENCE
              valueFrom:
                configMapKeyRef:
                  key: AUTH0_AUDIENCE
                  name: flask-api-env
            - name: AUTH0_DOMAIN
              valueFrom:
                configMapKeyRef:
                  key: AUTH0_DOMAIN
                  name: flask-api-env
            - name: CLIENT_ORIGIN_URL
              valueFrom:
                configMapKeyRef:
                  key: CLIENT_ORIGIN_URL
                  name: flask-api-env
          image: ' '
          name: flask-api
          ports:
            - containerPort: 8080
              protocol: TCP
          volumeMounts:
            - mountPath: /requirements.txt
              name: flask-api-cm0
              subPath: requirements.txt
            - mountPath: /api
              name: flask-api-cm1
            - mountPath: /api/db_interaction
              name: flask-api-cm2
            - mountPath: /api/messages
              name: flask-api-cm3
            - mountPath: /api/security
              name: flask-api-cm4
            - mountPath: /common/utils
              name: flask-api-cm5
            - mountPath: /gunicorn.conf.py
              name: flask-api-cm6
              subPath: gunicorn.conf.py
            - mountPath: /entrypoint.sh
              name: flask-api-cm7
              subPath: entrypoint.sh
      restartPolicy: Always
      volumes:
        - configMap:
            items:
              - key: requirements.txt
                path: requirements.txt
            name: flask-api-cm0
          name: flask-api-cm0
        - configMap:
            name: flask-api-cm1
          name: flask-api-cm1
        - configMap:
            name: flask-api-cm2
          name: flask-api-cm2
        - configMap:
            name: flask-api-cm3
          name: flask-api-cm3
        - configMap:
            name: flask-api-cm4
          name: flask-api-cm4
        - configMap:
            name: flask-api-cm5
          name: flask-api-cm5
        - configMap:
            items:
              - key: gunicorn.conf.py
                path: gunicorn.conf.py
            name: flask-api-cm6
          name: flask-api-cm6
        - configMap:
            items:
              - key: entrypoint.sh
                path: entrypoint.sh
            name: flask-api-cm7
          name: flask-api-cm7
  test: false
  triggers:
    - type: ConfigChange
    - imageChangeParams:
        automatic: true
        containerNames:
          - flask-api
        from:
          kind: ImageStreamTag
          name: flask-api:3.9.2-slim-buster
      type: ImageChange
