apiVersion: v1
data:
  VITE_APP_API_SERVER_URL: https://api-geo-acc-modelatlas.apps.cl01.cp.its.uu.nl
  VITE_APP_AUTH0_AUDIENCE: https://hello-world.example.com
  VITE_APP_AUTH0_CALLBACK_URL: http://127.0.0.1:8080
  VITE_APP_AUTH0_CLIENT_ID: mDQ7weveUxRP11YHAtUB8ZNPTwAYYDVs
  VITE_APP_AUTH0_DOMAIN: copernicus-model-atlas.eu.auth0.com
  VITE_APP_TRIAL_ENV: localdev
kind: ConfigMap
metadata:
  labels:
    io.kompose.service: frontend-react-frontend-react-env
  name: frontend-react-env
