apiVersion: apps.openshift.io/v1
kind: DeploymentConfig
metadata:
  labels:
    io.kompose.service: frontend-react
  name: frontend-react
spec:
  replicas: 1
  selector:
    io.kompose.service: frontend-react
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        io.kompose.service: frontend-react
    spec:
      containers:
        - command:
            - /bin/bash
            - /entrypoint.sh
          env:
            - name: VITE_APP_API_SERVER_URL
              valueFrom:
                configMapKeyRef:
                  key: VITE_APP_API_SERVER_URL
                  name: frontend-react-env
            - name: VITE_APP_AUTH0_AUDIENCE
              valueFrom:
                configMapKeyRef:
                  key: VITE_APP_AUTH0_AUDIENCE
                  name: frontend-react-env
            - name: VITE_APP_AUTH0_CALLBACK_URL
              valueFrom:
                configMapKeyRef:
                  key: VITE_APP_AUTH0_CALLBACK_URL
                  name: frontend-react-env
            - name: VITE_APP_AUTH0_CLIENT_ID
              valueFrom:
                configMapKeyRef:
                  key: VITE_APP_AUTH0_CLIENT_ID
                  name: frontend-react-env
            - name: VITE_APP_AUTH0_DOMAIN
              valueFrom:
                configMapKeyRef:
                  key: VITE_APP_AUTH0_DOMAIN
                  name: frontend-react-env
            - name: VITE_APP_TRIAL_ENV
              valueFrom:
                configMapKeyRef:
                  key: VITE_APP_TRIAL_ENV
                  name: frontend-react-env
          image: ' '
          name: frontend-react
          ports:
            - containerPort: 4000
              protocol: TCP
          volumeMounts:
            - mountPath: /entrypoint.sh
              name: frontend-react-hostpath0
            - mountPath: /dist/index.html
              name: frontend-react-hostpath1
            - mountPath: /dist/assets/images
              name: frontend-react-hostpath2
            - mountPath: /dist/assets/fonts/Merriweather
              name: frontend-react-hostpath3
            - mountPath: /dist/assets/fonts/Open_Sans
              name: frontend-react-hostpath4
            - mountPath: /dist/assets/fonts/Open_Sans/static
              name: frontend-react-hostpath5
      restartPolicy: Always
      volumes:
        - hostPath:
            path: C:\Users\moosc\Documents\3) Werk\CopernicusModelsOverview\Phase 4 Dev\application\frontend\entrypoint.sh
          name: frontend-react-hostpath0
        - hostPath:
            path: C:\Users\moosc\Documents\3) Werk\CopernicusModelsOverview\Phase 4 Dev\application\frontend\dist\index.html
          name: frontend-react-hostpath1
        - hostPath:
            path: C:\Users\moosc\Documents\3) Werk\CopernicusModelsOverview\Phase 4 Dev\application\frontend\dist\assets\images
          name: frontend-react-hostpath2
        - hostPath:
            path: C:\Users\moosc\Documents\3) Werk\CopernicusModelsOverview\Phase 4 Dev\application\frontend\dist\assets\fonts\Merriweather
          name: frontend-react-hostpath3
        - hostPath:
            path: C:\Users\moosc\Documents\3) Werk\CopernicusModelsOverview\Phase 4 Dev\application\frontend\dist\assets\fonts\Open_Sans
          name: frontend-react-hostpath4
        - hostPath:
            path: C:\Users\moosc\Documents\3) Werk\CopernicusModelsOverview\Phase 4 Dev\application\frontend\dist\assets\fonts\Open_Sans\static
          name: frontend-react-hostpath5
  test: false
  triggers:
    - type: ConfigChange
    - imageChangeParams:
        automatic: true
        containerNames:
          - frontend-react
        from:
          kind: ImageStreamTag
          name: frontend-react:16.15
      type: ImageChange
