apiVersion: image.openshift.io/v1
kind: ImageStream
metadata:
  labels:
    io.kompose.service: frontend-react
  name: frontend-react
spec:
  lookupPolicy:
    local: false
  tags:
    - from:
        kind: DockerImage
        name: node:16.15
      name: "16.15"
      referencePolicy:
        type: ""
