apiVersion: image.openshift.io/v1
kind: ImageStream
metadata:
  labels:
    io.kompose.service: postgres-access
  name: postgres-access
spec:
  lookupPolicy:
    local: false
  tags:
    - from:
        kind: DockerImage
        name: bitnami/postgresql:latest
      name: latest
      referencePolicy:
        type: ""
