apiVersion: v1
data:
  init_db.py: |
    import os
    import psycopg2
    from dotenv import load_dotenv


    load_dotenv()

    host = os.getenv("DB_HOST")
    database = os.getenv("DB_NAME")
    user = os.getenv("DB_USERNAME")
    password = os.getenv("DB_PASSWORD")

    conn = psycopg2.connect(
        host=host,
        database=database,
        user=user,
        password=password,
    )

    # Open a cursor to perform database operations
    cur = conn.cursor()

    # Execute a command: this creates a new table
    cur.execute("DROP TABLE IF EXISTS modellers;")
    cur.execute(
        "CREATE TABLE modellers (id serial PRIMARY KEY,"
        "name varchar (150) NOT NULL,"
        "model text,"
        "date_added date DEFAULT CURRENT_TIMESTAMP);"
    )

    # Insert data into the table

    cur.execute(
        "INSERT INTO modellers (name, model)" "VALUES (%s, %s)",
        ("Oreane Edelenbosch", "Mimosa"),
    )


    cur.execute(
        "INSERT INTO modellers (name, model)" "VALUES (%s, %s)",
        ("Kees Goldewijk", "Hyde"),
    )

    conn.commit()

    cur.close()
    conn.close()
  init_script.sql: |
    -- init_script.sql
    CREATE TABLE example_table (
        id SERIAL PRIMARY KEY,
        name VARCHAR(100)
    );
  run_init.sh: |
    #!/bin/bash



    export PGPASSWORD=$DB_PASSWORD

    # Run the SQL file using psql
    psql -h "$DB_HOST" -p "$DB_PORT" -U "$DB_USER" -d "$DB_NAME" -f /tmp/init_script.sql
kind: ConfigMap
metadata:
  labels:
    io.kompose.service: postgres-access
  name: postgres-access-cm0
