apiVersion: apps.openshift.io/v1
kind: DeploymentConfig
metadata:
  labels:
    io.kompose.service: postgres-access
  name: postgres-access
spec:
  replicas: 1
  selector:
    io.kompose.service: postgres-access
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        io.kompose.service: postgres-access
    spec:
      containers:
        - args:
            - sleep
            - infinity
          env:
            - name: PGDATABASE
              valueFrom:
                configMapKeyRef:
                  key: PGDATABASE
                  name: postgres-access-env
            - name: PGHOST
              valueFrom:
                configMapKeyRef:
                  key: PGHOST
                  name: postgres-access-env
            - name: PGPASSWORD
              value: /run/secrets/db-password
            - name: PGPORT
              valueFrom:
                configMapKeyRef:
                  key: PGPORT
                  name: postgres-access-env
            - name: PGUSER
              valueFrom:
                configMapKeyRef:
                  key: PGUSER
                  name: postgres-access-env
            - name: POSTGRESQL_PASSWORD
              valueFrom:
                configMapKeyRef:
                  key: POSTGRESQL_PASSWORD
                  name: postgres-access-env
            - name: POSTGRES_PASSWORD
              valueFrom:
                configMapKeyRef:
                  key: POSTGRES_PASSWORD
                  name: postgres-access-env
          image: ' '
          name: postgres-access
          ports:
            - containerPort: 5432
              protocol: TCP
          volumeMounts:
            - mountPath: /run/secrets
              name: db-password
              subPath: db-password
            - mountPath: /scripts
              name: postgres-access-cm0
      restartPolicy: Always
      volumes:
        - name: db-password
          secret:
            items:
              - key: db-password
                path: db-password
            secretName: db-password
        - configMap:
            name: postgres-access-cm0
          name: postgres-access-cm0
  test: false
  triggers:
    - type: ConfigChange
    - imageChangeParams:
        automatic: true
        containerNames:
          - postgres-access
        from:
          kind: ImageStreamTag
          name: postgres-access:latest
      type: ImageChange
