apiVersion: v1
data:
  DB_HOST: psql03.its.uu.nl
  DB_NAME: geo-prd-copernicus-model-atlas
  DB_PASSWORD: ANTeMA876_nuAdWE
  DB_PORT: "5432"
  DB_USERNAME: geo-prd-copernicus-model-atlas
  POSTGRES_PASSWORD: postgres
  POSTGRESQL_PASSWORD: postgres
kind: ConfigMap
metadata:
  labels:
    io.kompose.service: postgres-access-postgres-access-env
  name: postgres-access-env
