apiVersion: v1
kind: Service
metadata:
  labels:
    io.kompose.service: postgres-access
  name: postgres-access
spec:
  ports:
    - name: "5433"
      port: 5433
      targetPort: 5432
  selector:
    io.kompose.service: postgres-access
