apiVersion: v1
data:
  PGDATABASE: geo-prd-copernicus-model-atlas
  PGHOST: psql03.its.uu.nl
  PGPORT: "5432"
  PGUSER: geo-prd-copernicus-model-atlas
  POSTGRES_PASSWORD: postgres
  POSTGRESQL_PASSWORD: postgres
kind: ConfigMap
metadata:
  labels:
    io.kompose.service: postgres-access-postgres-access-env
  name: postgres-access-env
